var faculties = {
	BG : ['Arhitektonski fakultet', 'Biološki fakultet', 'Ekonomski fakultet',
			'Elektrotehnički fakultet', 'Fakultet za specijalnu edukaciju i rehabilitaciju',
			'Fakultet sporta i fizičkog vaspitanja', 'Fakultet bezbednosti',
			'Fakultet organizacionih nauka', 'Fakultet političkih nauka',
			'Fakultet za fizičku hemiju', 'Farmaceutski fakultet',
			'Filološki fakultet', 'Filozofski fakultet', 'Fizički fakultet',
			'Geografski fakultet', 'Građevinski fakultet', 'Hemijski fakultet',
			'Mašinski fakultet', 'Matematički fakultet', 'Medicinski fakultet',
			'Pravoslavni bogoslovski fakultet', 'Poljoprivredni fakultet','Pravni fakultet', 
			'Rudarsko-geološki fakultet', 'Saobraćajni fakultet' ,'Stomatološki fakultet',
			'Šumarski fakultet', 'Tehnički fakultet u Boru','Tehnološko-metalurški fakultet',
			'Učiteljski fakultet', 'Fakultet veterinarske medicine'],
	NS : ['Akademija umetnosti', 'Ekonomski fakultet',
			'Fakultet fizičke kulture', 'Filozofski fakultet',
			'Građevinski fakultet', 'Medicinski fakultet',
			'Pedagoški fakultet','Pravni fakultet', 
			'Prirodno-matematički fakultet',
			'Rudarsko-geološki fakultet',  'Tehnološki fakultet',
			'Tehnički fakultet Mihajlo Pupin',
			'Učiteljski fakultet na mađarskom nastavnom jeziku',
			'Fakultet veterinarske medicine'],
	NIS : ['Građevinsko-arhitektonski fakultet', 'Ekonomski fakultet',
			'Elektronski fakultet','Mašinski fakultet', 'Medicinski fakultet',
			'Pravni fakultet', 'Prirodno-matematički fakultet',
			'Tehnološki fakultet u Leskovcu',
			'Učiteljski fakultet u Vranju',
			'Fakultet umetnosti', 'Fakultet zaštite na radu',
			'Fakultet sporta i fizičkog vaspitanja', 'Filozofski fakultet'],
	KG : ['Agronomski fakultet', 'Ekonomski fakultet',
			'Fakultet za mašinstvo i građevinarstvo', 'Fakultet medicinskih nauka',
			'Fakultet pedagoških nauka', 'Pravni fakultet', 'Prirodno-matematički fakultet',
			'Fakultet tehničkih nauka', 'Učiteljski fakultet', 'Fakultet za hotelijerstvo i turizam',
			'Fakultet inženjerskih nauka', 'Filološko-umetnički fakultet'],
	NoviPazar : ['Departman za pravne nauke', 'Departman za ekonomske nauke',
					'Departman za filozofske nauke', 'Departman za filološke nauke',
					'Departman za matematičke nauke', 'Departman za tehničke nauke',
					'Departman za hemijsko-tehnološke nauke', 'Departman za biomedicinske nauke',
					'Departman za umetnost', 'Departman za multidisciplinarne nauke'],
	Pristina : ['Ekonomski fakultet', 'Pravni fakultet', 'Medicinski fakultet',
				'Učiteljski fakultet', 'Filozofski fakultet', 'Poljoprivredni fakultet',
				'Prirodno-matematički fakultet', 'Fakultet tehničkih nauka', 'Fakultet umetnosti',
				'Fakultet za fizičku kulturu'],
	UmetnostBG : ['Fakultet muzičke umetnosti', 'Fakultet muzičke umetnosti',
			'Fakultet dramskih umetnosti', 'Fakultet primenjenih umetnosti'],
	
}